const images = [
  // index in this array corresponds to index in src/assets/images/snapshot-i.png
  ["SGA", 1, 14],
  ["SGA", 1, 1],
  ["SGA", 1, 3],
  ["SGA", 1, 4],
  ["SGA", 1, 5],
  ["SGA", 1, 6],
  ["SGU", 1, 1],
  ["SGU", 1, 3],
  ["SGU", 1, 4],
  ["SGU", 1, 11],
  ["SGU", 1, 20],
  ["SGU", 2, 3],
  ["SGU", 2, 8],
  ["SGU", 2, 12],
  ["SGU", 2, 18],
  ["SGU", 2, 19],
  ["SGU", 2, 20],
  ["SGA", 1, 7],
  ["SGA", 1, 10],
  ["SGA", 1, 15],
  ["SGA", 1, 19],
  ["SGA", 2, 1],
  ["SGA", 2, 3],
  ["SGA", 2, 7],
  ["SGA", 2, 13],
  ["SGA", 2, 17],
  ["SGA", 2, 20],
  ["SGA", 3, 5],
  ["SGA", 3, 10],
  ["SGA", 3, 11],
  ["SGA", 3, 18],
  ["SGA", 3, 20],
  ["SGA", 4, 1],
  ["SGA", 4, 5],
  ["SGA", 4, 11],
  ["SGA", 4, 12],
  ["SGA", 4, 20],
  ["SGA", 5, 4],
  ["SGA", 5, 8],
  ["SGA", 5, 11],
  ["SGA", 5, 16],
  ["SGA", 5, 19],
  ["SGA", 5, 20],
  ["SGA", 3, 7],
  ["SG1", 10, 19],
  ["SG1", 1, 1],
  ["SG1", 1, 5],
  ["SG1", 1, 8],
  ["SG1", 1, 9],
  ["SG1", 1, 10],
  ["SG1", 1, 11],
  ["SG1", 1, 14],
  ["SG1", 1, 17],
  ["SG1", 1, 19],
  ["SG1", 1, 20],
  ["SG1", 1, 22],
  ["SG1", 2, 1],
  ["SG1", 2, 3],
  ["SG1", 2, 12],
  ["SG1", 2, 15],
  ["SG1", 2, 16],
  ["SG1", 2, 22],
  ["SG1", 3, 1],
  ["SG1", 3, 5],
  ["SG1", 3, 7],
  ["SG1", 3, 13],
  ["SG1", 3, 16],
  ["SG1", 3, 17],
  ["SG1", 3, 22],
  ["SG1", 4, 1],
  ["SG1", 4, 6],
  ["SG1", 4, 16],
  ["SG1", 4, 22],
  ["SG1", 5, 3],
  ["SG1", 5, 15],
  ["SG1", 5, 19],
  ["SG1", 5, 22],
  ["SG1", 6, 4],
  ["SG1", 6, 12],
  ["SG1", 6, 18],
  ["SG1", 6, 22],
  ["SG1", 7, 6],
  ["SG1", 7, 11],
  ["SG1", 7, 18],
  ["SG1", 7, 22],
  ["SG1", 8, 1],
  ["SG1", 8, 12],
  ["SG1", 8, 17],
  ["SG1", 9, 20],
  ["SG1", 9, 1],
  ["SG1", 9, 3],
  ["SG1", 9, 10],
  ["SG1", 9, 19],
  ["SG1", 10, 1],
  ["SG1", 10, 3],
  ["SG1", 10, 5],
  ["SG1", 10, 9],
  ["SG1", 10, 14],
  ["SG1", 10, 16],
  ["SG1", 10, 18],
  ["SG1", 10, 20],
];

// map days to snapshots (`images` indexes)
const epoch = 20250605;
const dailies = [
  45, 62, 13, 42, 67, 88, 35, 7, 64, 90, 91, 46, 58, 55, 94, 100, 31, 37, 74, 3,
  12, 52, 19, 30, 26, 99, 39, 2, 69, 87, 14, 73, 47, 72, 40, 43, 84, 15, 23, 6,
  59, 22, 82, 11, 4, 66, 75, 38, 20, 41, 51, 18, 83, 65, 28, 1, 27, 54, 68, 32,
  5, 86, 85, 34, 24, 50, 80, 56, 98, 49, 29, 57, 96, 79, 70, 25, 60, 9, 48, 61,
  17, 71, 77, 10, 93, 21, 92, 16, 81, 8, 53, 78, 63, 97, 44, 36, 76, 89, 95, 33,
];

const stargate = {
  SG1: {
    1: {
      1: { name: "Children of the Gods (Part 1)" },
      2: { name: "Children of the Gods (Part 2)" },
      3: { name: "The Enemy Within" },
      4: { name: "Emancipation" },
      5: { name: "The Broca Divide" },
      6: { name: "The First Commandment" },
      7: { name: "Cold Lazarus" },
      8: { name: "The Nox" },
      9: { name: "Brief Candle" },
      10: { name: "Thor's Hammer" },
      11: { name: "The Torment of Tantalus" },
      12: { name: "Bloodlines" },
      13: { name: "Fire and Water" },
      14: { name: "Hathor" },
      15: { name: "Singularity" },
      16: { name: "Cor-Ai" },
      17: { name: "Enigma" },
      18: { name: "Solitudes" },
      19: { name: "Tin Man" },
      20: { name: "There But for the Grace of God" },
      21: { name: "Politics" },
      22: { name: "Within the Serpent's Grasp" },
    },
    2: {
      1: { name: "The Serpent's Lair" },
      2: { name: "In the Line of Duty" },
      3: { name: "Prisoners" },
      4: { name: "The Gamekeeper" },
      5: { name: "Need" },
      6: { name: "Thor's Chariot" },
      7: { name: "Message in a Bottle" },
      8: { name: "Family" },
      9: { name: "Secrets" },
      10: { name: "Bane" },
      11: { name: "The Tok'ra (Part 1)" },
      12: { name: "The Tok'ra (Part 2)" },
      13: { name: "Spirits" },
      14: { name: "Touchstone" },
      15: { name: "The Fifth Race" },
      16: { name: "A Matter of Time" },
      17: { name: "Holiday" },
      18: { name: "Serpent's Song" },
      19: { name: "One False Step" },
      20: { name: "Show and Tell" },
      21: { name: "1969" },
      22: { name: "Out of Mind" },
    },
    3: {
      1: { name: "Into the Fire" },
      2: { name: "Seth" },
      3: { name: "Fair Game" },
      4: { name: "Legacy" },
      5: { name: "Learning Curve" },
      6: { name: "Point of View" },
      7: { name: "Deadman Switch" },
      8: { name: "Demons" },
      9: { name: "Rules of Engagement" },
      10: { name: "Forever in a Day" },
      11: { name: "Past and Present" },
      12: { name: "Jolinar's Memories" },
      13: { name: "The Devil You Know" },
      14: { name: "Foothold" },
      15: { name: "Pretense" },
      16: { name: "Urgo" },
      17: { name: "A Hundred Days" },
      18: { name: "Shades of Grey" },
      19: { name: "New Ground" },
      20: { name: "Maternal Instinct" },
      21: { name: "Crystal Skull" },
      22: { name: "Nemesis" },
    },
    4: {
      1: { name: "Small Victories" },
      2: { name: "The Other Side" },
      3: { name: "Upgrades" },
      4: { name: "Crossroads" },
      5: { name: "Divide and Conquer" },
      6: { name: "Window of Opportunity" },
      7: { name: "Watergate" },
      8: { name: "The First Ones" },
      9: { name: "Scorched Earth" },
      10: { name: "Beneath the Surface" },
      11: { name: "Point of No Return" },
      12: { name: "Tangent" },
      13: { name: "The Curse" },
      14: { name: "The Serpent's Venom" },
      15: { name: "Chain Reaction" },
      16: { name: "2010" },
      17: { name: "Absolute Power" },
      18: { name: "The Light" },
      19: { name: "Prodigy" },
      20: { name: "Entity" },
      21: { name: "Double Jeopardy" },
      22: { name: "Exodus" },
    },
    5: {
      1: { name: "Enemies" },
      2: { name: "Threshold" },
      3: { name: "Ascension" },
      4: { name: "The Fifth Man" },
      5: { name: "Red Sky" },
      6: { name: "Rite of Passage" },
      7: { name: "Beast of Burden" },
      8: { name: "The Tomb" },
      9: { name: "Between Two Fires" },
      10: { name: "2001" },
      11: { name: "Desperate Measures" },
      12: { name: "Wormhole X-Treme!" },
      13: { name: "Proving Ground" },
      14: { name: "48 Hours" },
      15: { name: "Summit" },
      16: { name: "Last Stand" },
      17: { name: "Fail Safe" },
      18: { name: "The Warrior" },
      19: { name: "Menace" },
      20: { name: "The Sentinel" },
      21: { name: "Meridian" },
      22: { name: "Revelations" },
    },
    6: {
      1: { name: "Redemption (Part 1)" },
      2: { name: "Redemption (Part 2)" },
      3: { name: "Descent" },
      4: { name: "Frozen" },
      5: { name: "Nightwalkers" },
      6: { name: "Abyss" },
      7: { name: "Shadow Play" },
      8: { name: "The Other Guys" },
      9: { name: "Allegiance" },
      10: { name: "Cure" },
      11: { name: "Prometheus" },
      12: { name: "Unnatural Selection" },
      13: { name: "Sight Unseen" },
      14: { name: "Smoke & Mirrors" },
      15: { name: "Paradise Lost" },
      16: { name: "Metamorphosis" },
      17: { name: "Disclosure" },
      18: { name: "Forsaken" },
      19: { name: "The Changeling" },
      20: { name: "Memento" },
      21: { name: "Prophecy" },
      22: { name: "Full Circle" },
    },
    7: {
      1: { name: "Fallen" },
      2: { name: "Homecoming" },
      3: { name: "Fragile Balance" },
      4: { name: "Orpheus" },
      5: { name: "Revisions" },
      6: { name: "Lifeboat" },
      7: { name: "Enemy Mine" },
      8: { name: "Space Race" },
      9: { name: "Avenger 2.0" },
      10: { name: "Birthright" },
      11: { name: "Evolution (Part 1)" },
      12: { name: "Evolution (Part 2)" },
      13: { name: "Grace" },
      14: { name: "Fallout" },
      15: { name: "Chimera" },
      16: { name: "Death Knell" },
      17: { name: "Heroes (Part 1)" },
      18: { name: "Heroes (Part 2)" },
      19: { name: "Resurrection" },
      20: { name: "Inauguration" },
      21: { name: "Lost City (Part 1)" },
      22: { name: "Lost City (Part 2)" },
    },
    8: {
      1: { name: "New Order (Part 1)" },
      2: { name: "New Order (Part 2)" },
      3: { name: "Lockdown" },
      4: { name: "Zero Hour" },
      5: { name: "Icon" },
      6: { name: "Avatar" },
      7: { name: "Affinity" },
      8: { name: "Covenant" },
      9: { name: "Sacrifices" },
      10: { name: "Endgame" },
      11: { name: "Gemini" },
      12: { name: "Prometheus Unbound" },
      13: { name: "It's Good to Be King" },
      14: { name: "Full Alert" },
      15: { name: "Citizen Joe" },
      16: { name: "Reckoning (Part 1)" },
      17: { name: "Reckoning (Part 2)" },
      18: { name: "Threads" },
      19: { name: "Moebius (Part 1)" },
      20: { name: "Moebius (Part 2)" },
    },
    9: {
      1: { name: "Avalon (Part 1)" },
      2: { name: "Avalon (Part 2)" },
      3: { name: "Origin" },
      4: { name: "The Ties That Bind" },
      5: { name: "The Powers That Be" },
      6: { name: "Beachhead" },
      7: { name: "Ex Deus Machina" },
      8: { name: "Babylon" },
      9: { name: "Prototype" },
      10: { name: "The Fourth Horseman (Part 1)" },
      11: { name: "The Fourth Horseman (Part 2)" },
      12: { name: "Collateral Damage" },
      13: { name: "Ripple Effect" },
      14: { name: "Stronghold" },
      15: { name: "Ethon" },
      16: { name: "Off the Grid" },
      17: { name: "The Scourge" },
      18: { name: "Arthur's Mantle" },
      19: { name: "Crusade" },
      20: { name: "Camelot" },
    },
    10: {
      1: { name: "Flesh and Blood" },
      2: { name: "Morpheus" },
      3: { name: "The Pegasus Project" },
      4: { name: "Insiders" },
      5: { name: "Uninvited" },
      6: { name: "200" },
      7: { name: "Counterstrike" },
      8: { name: "Memento Mori" },
      9: { name: "Company of Thieves" },
      10: { name: "The Quest (Part 1)" },
      11: { name: "The Quest (Part 2)" },
      12: { name: "Line in the Sand" },
      13: { name: "The Road Not Taken" },
      14: { name: "The Shroud" },
      15: { name: "Bounty" },
      16: { name: "Bad Guys" },
      17: { name: "Talion" },
      18: { name: "Family Ties" },
      19: { name: "Dominion" },
      20: { name: "Unending" },
    },
  },
  SGA: {
    1: {
      1: { name: "Rising (Part 1)" },
      2: { name: "Rising (Part 2)" },
      3: { name: "Hide and Seek" },
      4: { name: "Thirty Eight Minutes" },
      5: { name: "Suspicion" },
      6: { name: "Childhood's End" },
      7: { name: "Poisoning the Well" },
      8: { name: "Underground" },
      9: { name: "Home" },
      10: { name: "The Storm" },
      11: { name: "The Eye" },
      12: { name: "The Defiant One" },
      13: { name: "Hot Zone" },
      14: { name: "Sanctuary" },
      15: { name: "Before I Sleep" },
      16: { name: "The Brotherhood" },
      17: { name: "Letters from Pegasus" },
      18: { name: "The Gift" },
      19: { name: "The Siege (Part 1)" },
      20: { name: "The Siege (Part 2)" },
    },
    2: {
      1: { name: "The Siege (Part 3)" },
      2: { name: "The Intruder" },
      3: { name: "Runner" },
      4: { name: "Duet" },
      5: { name: "Condemned" },
      6: { name: "Trinity" },
      7: { name: "Instinct" },
      8: { name: "Conversion" },
      9: { name: "Aurora" },
      10: { name: "The Lost Boys" },
      11: { name: "The Hive" },
      12: { name: "Epiphany" },
      13: { name: "Critical Mass" },
      14: { name: "Grace Under Pressure" },
      15: { name: "The Tower" },
      16: { name: "The Long Goodbye" },
      17: { name: "Coup D'État" },
      18: { name: "Michael" },
      19: { name: "Inferno" },
      20: { name: "Allies" },
      21: { name: "The Lost City" },
    },
    3: {
      1: { name: "No Man's Land" },
      2: { name: "Misbegotten" },
      3: { name: "Irresistible" },
      4: { name: "Sateda" },
      5: { name: "Progeny" },
      6: { name: "The Real World" },
      7: { name: "Common Ground" },
      8: { name: "McKay and Mrs. Miller" },
      9: { name: "Phantoms" },
      10: { name: "The Return (Part 1)" },
      11: { name: "The Return (Part 2)" },
      12: { name: "Echoes" },
      13: { name: "Irresponsible" },
      14: { name: "Tao of Rodney" },
      15: { name: "The Game" },
      16: { name: "The Ark" },
      17: { name: "Sunday" },
      18: { name: "Submersion" },
      19: { name: "Vengeance" },
      20: { name: "First Strike" },
    },
    4: {
      1: { name: "Adrift" },
      2: { name: "Lifeline" },
      3: { name: "Reunion" },
      4: { name: "Doppelganger" },
      5: { name: "Travelers" },
      6: { name: "Tabula Rasa" },
      7: { name: "Missing" },
      8: { name: "The Seer" },
      9: { name: "Miller's Crossing" },
      10: { name: "This Mortal Coil" },
      11: { name: "Be All My Sins Remember'd" },
      12: { name: "Spoils of War" },
      13: { name: "Quarantine" },
      14: { name: "The Kindred (Part 1)" },
      15: { name: "The Kindred (Part 2)" },
      16: { name: "The Last Man" },
      17: { name: "Search and Rescue" },
      18: { name: "The Seed" },
      19: { name: "Broken Ties" },
      20: { name: "The Daedalus Variations" },
    },
    5: {
      1: { name: "Search and Rescue" },
      2: { name: "The Seed" },
      3: { name: "Broken Ties" },
      4: { name: "The Daedalus Variations" },
      5: { name: "Ghost in the Machine" },
      6: { name: "The Shrine" },
      7: { name: "Whispers" },
      8: { name: "The Queen" },
      9: { name: "Tracker" },
      10: { name: "First Contact" },
      11: { name: "The Lost Tribe" },
      12: { name: "Outsiders" },
      13: { name: "Inquisition" },
      14: { name: "The Prodigal" },
      15: { name: "Remnants" },
      16: { name: "Brain Storm" },
      17: { name: "Infection" },
      18: { name: "Identity" },
      19: { name: "Vegas" },
      20: { name: "Enemy at the Gate" },
    },
  },
  SGU: {
    1: {
      1: { name: "Air (Part 1)" },
      2: { name: "Air (Part 2)" },
      3: { name: "Air (Part 3)" },
      4: { name: "Darkness" },
      5: { name: "Light" },
      6: { name: "Water" },
      7: { name: "Earth" },
      8: { name: "Time" },
      9: { name: "Life" },
      10: { name: "Justice" },
      11: { name: "Space" },
      12: { name: "Divided" },
      13: { name: "Faith" },
      14: { name: "Human" },
      15: { name: "Lost" },
      16: { name: "Sabotage" },
      17: { name: "Pain" },
      18: { name: "Subversion" },
      19: { name: "Incursion (Part 1)" },
      20: { name: "Incursion (Part 2)" },
    },
    2: {
      1: { name: "Intervention" },
      2: { name: "Aftermath" },
      3: { name: "Awakening" },
      4: { name: "Pathogen" },
      5: { name: "Cloverdale" },
      6: { name: "Trial and Error" },
      7: { name: "The Greater Good" },
      8: { name: "Malice" },
      9: { name: "Visitation" },
      10: { name: "Resurgence" },
      11: { name: "Deliverance" },
      12: { name: "Twin Destinies" },
      13: { name: "Alliances" },
      14: { name: "Hope" },
      15: { name: "Seizure" },
      16: { name: "The Hunt" },
      17: { name: "Common Descent" },
      18: { name: "Epilogue" },
      19: { name: "Blockade" },
      20: { name: "Gauntlet" },
    },
  },
};
